### PR TITLE
Added openui5_deploy_abap task

### PR DESCRIPTION
**Pull request by TheGreenToaster**
@wolframK 

I have some concerns about including the node-rfc dependency in the repository. Might need to be broken out into another repo to allow for non node-rfc compliant clients

### CODE REVIEW

**Comment by TheGreenToaster** [comment]
It looks like the build failed trying to install node-rfc. Might not work well in this repo.

**Comment by RandomByte** [comment]
Hey @TheGreenToaster,

Thank you for your Pull Request.

So far, grunt-openui5 does not contain tasks for deploying an application. As the ABAP deployment is just one of many scenarios it might make sense to split this into a separate repository. Is there any reason you think it should be put into this one?

We are discussing this internally right now and keep you posted!

**Comment by TheGreenToaster** [comment]
Hey @RandomByte 
I don't have any reason to think it should go here other than its with other ui5 oriented grunt tasks.

**Comment by RandomByte** [comment]
We discussed this with some colleagues and it looks like the ABAP upload process is being reworked at the moment. An easier interface is planned and with that probably a new grunt task.

We will therefore not add this soon-to-be-deprecated task to one of our repositories. If you like to, you can of course promote your fork or make this a repository on it's own (containing just the upload task) with dependencies to grunt-openui5.

Anyway, thanks again for your effort!

**Pull request closed without merging**
