### PR TITLE
[INTERNAL] CI: Test on Node.js v16

### PR DESCRIPTION
**Pull request by matz3**

### CODE REVIEW

**Review by codeworrior — COMMENTED** [review]
Strange, I don't get the difference to less-openui5. There, the configuration looks the same to me, but in less-openui5, only node versions 10, 12 and 14 are tested in addition to 16, but here also version 15 is running and blocks the merge.

**Comment by matz3** [comment]
It's not running, it's configured as "Required" check.
This configuration needs to be changed, which hasn't happened, yet.

I'll do so now, and then we will be able to merge. But I wasn't able to add the new Node 16 runs as "Required". Those were not showing up in the list of checks. I need to follow-up on this.

**Comment by matz3** [comment]
Ok, so here it worked 👍🏻

**Review by codeworrior — APPROVED** [review]
LGMT now.

**Pull request merged**
