### PR TITLE
Disable browser cache in the development server

### PR DESCRIPTION
**Pull request by pavelkornev**

### CODE REVIEW

**Comment by RandomByte** [comment]
Hey Pavel,

Do you have a scenario where the behavior causes issues?

From what I'm experiencing, the Grunt tooling currently sets the correct headers for invalidating the cache of changed resources. For example when changing a single *.js file on disk, it is being re-loaded while others are read from the cache, slightly improving the overall loading time.

Merlin

**Comment by pavelkornev** [comment]
Hey Merlin,

you wasn't involved in the discussion by email. I've just forwarded it to you.

TL;DL. It's not about caching but about CSP headers which are trimmed by "send" package (used by serve-static) when 304 (Not Modified) happens.

Best,
Pavel

**Comment by pavelkornev** [comment]
?

**Comment by RandomByte** [comment]
Hi Pavel,

Has there been any update on https://github.com/pillarjs/send/pull/164 ?

I would rather like to see this fixed upstream. There is afaik no actual issue with the tooling sending 304 (Not Modified) status for resources that have not been modified.

In some scenarios, removing this caching behavior might even slow down development workflows I guess?

**Comment by matz3** [comment]
@pavelkornev Sorry for not following-up... is this still relevant?

**Comment by pavelkornev** [comment]
@matz3 as this project is deprecated (isn't it?), I'm fine with closing this PR

**Pull request closed without merging**
